/* eslint-disable */
/**
 * QX-NewsItem — one row component for every news story rendered across QSweb,
 * Quotestream Mobile, Research Hub, and QX/QMOD widgets.
 *
 * Configured by props. Presets are named prop bundles, not separate components:
 * choosing a preset sets defaults; individual props stay overridable.
 *
 * Spec: qxnewsitemspec.md (Sam Fernandes / Design, Aug 2026).
 *
 * Renders as a native <a> so the whole row is one link target and one tab stop.
 * Accessible name is the headline alone; source / time / symbol / topic /
 * sentiment stay in DOM order after the title even when metaPosition="top"
 * reorders them visually via CSS.
 *
 * Depends only on QX design tokens (--qx-*). Namespaced under .qx-newsitem so
 * third-party page CSS can't leak in. Every var() carries a resolved fallback.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require('react'));
  else root.QXNewsItem = factory(root.React);
})(typeof self !== 'undefined' ? self : this, function (React) {
  const h = React.createElement;

  /* ---- Preset bundles ------------------------------------------------- */
  const PRESETS = {
    feed:      { metaPosition: 'top',    titleLines: 2, showDescription: true,  descriptionLines: 2, showImage: true,  imagePosition: 'leading',  showBadgeRow: true },
    editorial: { metaPosition: 'bottom', titleLines: 2, showDescription: true,  descriptionLines: 3, showImage: true,  imagePosition: 'trailing', showBadgeRow: true },
    compact:   { metaPosition: 'top',    titleLines: 1, showDescription: false, descriptionLines: 1, showImage: false, imagePosition: 'leading',  showBadgeRow: true },
    lead:      { metaPosition: 'top',    titleLines: 2, showDescription: true,  descriptionLines: 3, showImage: true,  imagePosition: 'above',    showBadgeRow: true },
    embed:     { metaPosition: 'top',    titleLines: 1, showDescription: false, descriptionLines: 1, showImage: false, imagePosition: 'leading',  showBadgeRow: false, minimalMeta: true },
  };

  const pick = (val, presetVal, fallback) =>
    val !== undefined ? val : (presetVal !== undefined ? presetVal : fallback);

  /* ---- Sub-marks ------------------------------------------------------ */
  // Sentiment pairs a shape with the semantic tone token (never colour alone).
  function SentimentIcon({ sentiment }) {
    const map = {
      positive: { glyph: '▲', label: 'Positive sentiment', cls: 'qx-ni-pos' },
      negative: { glyph: '▼', label: 'Negative sentiment', cls: 'qx-ni-neg' },
      neutral:  { glyph: '■', label: 'Neutral sentiment',  cls: 'qx-ni-neu' },
    };
    const s = map[sentiment] || map.neutral;
    return h('span', { className: 'qx-ni-sentiment ' + s.cls, role: 'img', 'aria-label': s.label, title: s.label }, s.glyph);
  }

  // AI-derived content is labelled explicitly with an accessible name + tooltip.
  function AIIcon({ label }) {
    const name = label || 'Summary generated by AI';
    return h('span', { className: 'qx-ni-ai', role: 'img', 'aria-label': name, title: name },
      h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'currentColor', 'aria-hidden': 'true' },
        h('path', { d: 'M12 2l1.9 5.3L19 9.2l-5.1 1.9L12 16l-1.9-4.9L5 9.2l5.1-1.9L12 2zM19 14l.9 2.5L22 17.4l-2.1.9L19 21l-.9-2.7L16 17.4l2.1-.9L19 14z' })));
  }

  function LockIcon() {
    return h('svg', { className: 'qx-ni-lockglyph', width: 14, height: 14, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': 'true' },
      h('rect', { x: 3, y: 11, width: 18, height: 10, rx: 2 }),
      h('path', { d: 'M7 11V7a5 5 0 0 1 10 0v4' }));
  }

  /* ---- Media ---------------------------------------------------------- */
  function Media({ src, sourceInitials, alt }) {
    if (src) {
      return h('div', { className: 'qx-ni-media' },
        h('img', { className: 'qx-ni-thumb', src, alt: alt || '', loading: 'lazy' }));
    }
    // Branded fallback tile keeps alignment stable across a feed with patchy images.
    return h('div', { className: 'qx-ni-media qx-ni-media-fallback', 'aria-hidden': 'true' },
      h('span', { className: 'qx-ni-fallback-mark' }, (sourceInitials || 'QM').slice(0, 3)));
  }

  /* ---- Skeleton (mirrors configured anatomy) -------------------------- */
  function Skeleton({ r }) {
    const lines = (n, w) => Array.from({ length: n }, (_, i) =>
      h('span', { key: i, className: 'qx-ni-sk-line', style: { width: (Array.isArray(w) ? w[i] : w) || '100%' } }));
    const body = h('div', { className: 'qx-ni-sk-body' },
      r.metaPosition === 'top' ? h('span', { className: 'qx-ni-sk-meta' }) : null,
      h('div', { className: 'qx-ni-sk-title' }, lines(r.titleLines === 'full' ? 2 : r.titleLines, ['92%', '68%'])),
      r.showDescription ? h('div', { className: 'qx-ni-sk-desc' }, lines(Math.min(r.descriptionLines, 3), ['100%', '96%', '54%'])) : null,
      r.showBadgeRow ? h('div', { className: 'qx-ni-sk-badges' }, h('span', {}), h('span', {})) : null,
      r.metaPosition === 'bottom' ? h('span', { className: 'qx-ni-sk-meta' }) : null,
    );
    const media = r.showImage ? h('div', { className: 'qx-ni-sk-media' }) : null;
    return h('div', { className: 'qx-ni-inner' },
      r.imagePosition === 'trailing' ? [body, media] : [media, body].filter(Boolean));
  }

  /* ---- Component ------------------------------------------------------ */
  function QXNewsItem(props) {
    const {
      preset = 'feed',
      density = 'comfortable',
      state = 'default',
      // content
      title = 'Headline goes here',
      description = 'Story snippet goes here',
      source = 'Source name',
      timestamp = '2h ago',
      datetime,
      image,
      sourceInitials,
      imageAlt,
      symbol,
      symbolChange,
      sentiment = 'neutral',
      topic,
      aiLabel,
      signalLevel = 'high',
      href = '#',
      onActivate,
      ...rest
    } = props;

    const p = PRESETS[preset] || PRESETS.feed;
    const r = {
      metaPosition:     pick(props.metaPosition,     p.metaPosition,     'top'),
      titleLines:       pick(props.titleLines,       p.titleLines,       2),
      showDescription:  pick(props.showDescription,  p.showDescription,  true),
      descriptionLines: pick(props.descriptionLines, p.descriptionLines, 2),
      showImage:        pick(props.showImage,        p.showImage,        true),
      imagePosition:    pick(props.imagePosition,    p.imagePosition,    'leading'),
      showBadgeRow:     pick(props.showBadgeRow,     p.showBadgeRow,     true),
      showSymbol:       pick(props.showSymbol,       undefined,          !!symbol),
      showSentiment:    pick(props.showSentiment,    undefined,          false),
      showAI:           pick(props.showAI,           undefined,          false),
      showTopic:        pick(props.showTopic,        undefined,          !!topic),
      showSignalSpine:  pick(props.showSignalSpine,  undefined,          false),
      minimalMeta:      p.minimalMeta || false,
    };

    const isLoading = state === 'loading';
    const isLocked = state === 'locked';
    const isRead = state === 'read';

    const dataAttrs = {
      className: 'qx-newsitem',
      'data-preset': preset,
      'data-density': density,
      'data-state': state,
      'data-image-pos': r.showImage ? r.imagePosition : 'none',
      'data-meta-pos': r.metaPosition,
      'data-signal': r.showSignalSpine ? signalLevel : undefined,
      'data-title-lines': r.titleLines,
      'data-desc-lines': r.descriptionLines,
    };

    // Loading skeleton is not a link and not focusable.
    if (isLoading) {
      return h('div', Object.assign({}, dataAttrs, { 'aria-hidden': 'true', role: 'presentation' }),
        h(Skeleton, { r }));
    }

    /* Badge row — Symbol chip · Sentiment · AI · Topic. Collapses entirely
       when all four are off, with no reserved space. */
    const badges = [];
    if (r.showBadgeRow) {
      if (r.showSymbol && symbol) {
        badges.push(h('span', { key: 'sym', className: 'qx-ni-symbol' + (symbolChange != null ? (symbolChange >= 0 ? ' qx-ni-up' : ' qx-ni-down') : '') },
          symbol,
          symbolChange != null ? h('span', { className: 'qx-ni-symbol-chg' }, (symbolChange >= 0 ? '+' : '') + symbolChange.toFixed(2) + '%') : null));
      }
      if (r.showSentiment) badges.push(h(SentimentIcon, { key: 'sent', sentiment }));
      if (r.showAI) badges.push(h(AIIcon, { key: 'ai', label: aiLabel }));
      if (r.showTopic && topic) badges.push(h('span', { key: 'topic', className: 'qx-ni-topic' }, topic));
    }
    const badgeRow = badges.length ? h('div', { className: 'qx-ni-badges' }, badges) : null;

    /* Meta row — source · separator · relative time. One meta row at a time.
       Timestamp wrapped in <time datetime> with the absolute value. */
    const metaRow = h('div', { className: 'qx-ni-meta' },
      h('span', { className: 'qx-ni-source' }, source),
      h('span', { className: 'qx-ni-sep', 'aria-hidden': 'true' }, '·'),
      h('time', datetime ? { className: 'qx-ni-time', dateTime: datetime } : { className: 'qx-ni-time' }, timestamp),
    );

    const titleEl = h('h3', { className: 'qx-ni-title' }, title);
    const descEl = (r.showDescription && !r.minimalMeta)
      ? h('p', { className: 'qx-ni-desc' }, description)
      : null;

    // DOM order: title → description → badges → meta (accessible name is the
    // headline; everything else follows it). CSS `order` lifts meta to the top
    // visually when metaPosition="top".
    const body = h('div', { className: 'qx-ni-body' },
      titleEl,
      descEl,
      badgeRow,
      metaRow,
      isLocked ? h('span', { id: 'qx-ni-lock-desc', className: 'qx-sr-only' }, 'This story requires an upgrade to read.') : null,
    );

    const media = r.showImage
      ? h('div', { className: 'qx-ni-media-wrap' },
          h(Media, { src: image, sourceInitials, alt: imageAlt }),
          isLocked ? h('span', { className: 'qx-ni-media-lock', 'aria-hidden': 'true' }, h(LockIcon)) : null)
      : null;

    const inner = h('div', { className: 'qx-ni-inner' },
      r.imagePosition === 'trailing' ? [body, media] : [media, body]);

    const handleClick = onActivate ? (e) => { e.preventDefault(); onActivate(props); } : undefined;

    return h('a', Object.assign({
      href,
      onClick: handleClick,
      'aria-label': title,
      'aria-describedby': isLocked ? 'qx-ni-lock-desc' : undefined,
    }, dataAttrs, rest),
      isLocked ? h('span', { className: 'qx-ni-lock-badge' }, h(LockIcon), 'Upgrade to read') : null,
      inner);
  }

  QXNewsItem.PRESETS = PRESETS;
  return QXNewsItem;
});
