/* eslint-disable */
/**
 * QX-NewsItem — one row component for every news story rendered across QSweb,
 * Quotestream Mobile, Research Hub, and QX/QMOD widgets.
 *
 * Configured by props. Presets are named prop bundles, not separate components:
 * choosing a preset sets defaults; individual props stay overridable.
 *
 * Spec: qxnewsitemspec.md (Sam Fernandes / Design, Aug 2026).
 *
 * Renders as a native <a> so the whole row is one link target and one tab stop.
 * Accessible name is the headline alone; source / time / symbol / topic /
 * sentiment stay in DOM order after the title even when metaPosition="top"
 * reorders them visually via CSS.
 *
 * Depends only on QX design tokens (--qx-*). Namespaced under .qx-newsitem so
 * third-party page CSS can't leak in. Every var() carries a resolved fallback.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require('react'), (function () { try { return require('react-dom'); } catch (e) { return null; } })());
  else root.QXNewsItem = factory(root.React, root.ReactDOM);
})(typeof self !== 'undefined' ? self : this, function (React, ReactDOM) {
  const h = React.createElement;
  const { useState, useRef, useEffect, useCallback } = React;

  /* ---- Preset bundles ------------------------------------------------- */
  const PRESETS = {
    feed:      { metaPosition: 'top',    titleLines: 2, showDescription: true,  descriptionLines: 2, showImage: true,  imagePosition: 'leading',  showBadgeRow: true },
    editorial: { metaPosition: 'bottom', titleLines: 2, showDescription: true,  descriptionLines: 3, showImage: true,  imagePosition: 'trailing', showBadgeRow: true },
    compact:   { metaPosition: 'top',    titleLines: 1, showDescription: false, descriptionLines: 1, showImage: false, imagePosition: 'leading',  showBadgeRow: true },
    lead:      { metaPosition: 'top',    titleLines: 2, showDescription: true,  descriptionLines: 3, showImage: true,  imagePosition: 'above',    showBadgeRow: true },
    embed:     { metaPosition: 'top',    titleLines: 1, showDescription: false, descriptionLines: 1, showImage: false, imagePosition: 'leading',  showBadgeRow: false, minimalMeta: true },
  };

  const pick = (val, presetVal, fallback) =>
    val !== undefined ? val : (presetVal !== undefined ? presetVal : fallback);

  /* ---- Sub-marks ------------------------------------------------------ */
  // Sentiment pairs a shape with the semantic tone token (never colour alone).
  function SentimentIcon({ sentiment }) {
    const map = {
      positive: { glyph: '▲', word: 'Positive', label: 'Positive sentiment', cls: 'qx-ni-pos' },
      negative: { glyph: '▼', word: 'Negative', label: 'Negative sentiment', cls: 'qx-ni-neg' },
      neutral:  { glyph: '■', word: 'Neutral',  label: 'Neutral sentiment',  cls: 'qx-ni-neu' },
    };
    const s = map[sentiment] || map.neutral;
    return h('span', { className: 'qx-ni-sentiment ' + s.cls, role: 'img', 'aria-label': s.label, title: s.label },
      h('span', { className: 'qx-ni-sentiment-glyph', 'aria-hidden': 'true' }, s.glyph), s.word);
  }

  const AISparkle = () =>
    h('svg', { width: 12, height: 12, viewBox: '0 0 24 24', fill: 'currentColor', 'aria-hidden': 'true' },
      h('path', { d: 'M12 2l1.9 5.3L19 9.2l-5.1 1.9L12 16l-1.9-4.9L5 9.2l5.1-1.9L12 2zM19 14l.9 2.5L22 17.4l-2.1.9L19 21l-.9-2.7L16 17.4l2.1-.9L19 14z' }));
  const RefreshIcon = () =>
    h('svg', { width: 13, height: 13, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': 'true' },
      h('path', { d: 'M21 12a9 9 0 1 1-2.64-6.36' }), h('path', { d: 'M21 3v6h-6' }));

  // AI-derived content — labelled affordance that opens an AI summary popover.
  function AIIcon({ label, summary, updated }) {
    const name = label || 'Summary generated by AI';
    const [open, setOpen] = useState(false);
    const [pos, setPos] = useState({ left: 0, top: 0 });
    const btnRef = useRef(null);
    const popRef = useRef(null);

    const place = useCallback(() => {
      const btn = btnRef.current, pop = popRef.current;
      if (!btn || !pop) return;
      const rc = btn.getBoundingClientRect(), w = pop.offsetWidth, hgt = pop.offsetHeight, gap = 8, m = 12;
      let left = Math.max(m, Math.min(rc.right - w, window.innerWidth - w - m));
      let top = rc.bottom + gap;
      if (top + hgt > window.innerHeight - m && rc.top - gap - hgt > m) top = rc.top - gap - hgt;
      setPos({ left, top: Math.max(m, Math.min(top, window.innerHeight - hgt - m)) });
    }, []);

    useEffect(() => {
      if (!open) return;
      place();
      const onDown = (e) => { if (popRef.current && !popRef.current.contains(e.target) && !btnRef.current.contains(e.target)) setOpen(false); };
      const onKey = (e) => { if (e.key === 'Escape') { e.preventDefault(); setOpen(false); btnRef.current && btnRef.current.focus(); } };
      document.addEventListener('mousedown', onDown, true);
      document.addEventListener('keydown', onKey, true);
      window.addEventListener('resize', place, true);
      window.addEventListener('scroll', place, true);
      return () => {
        document.removeEventListener('mousedown', onDown, true);
        document.removeEventListener('keydown', onKey, true);
        window.removeEventListener('resize', place, true);
        window.removeEventListener('scroll', place, true);
      };
    }, [open, place]);

    const toggle = (e) => { e.preventDefault(); e.stopPropagation(); setOpen(o => !o); };
    const onKeyDown = (e) => { if (e.key === 'Enter' || e.key === ' ' || e.key === 'Spacebar') toggle(e); };

    const bullets = summary || [
      'Key drivers behind the move are summarized here in two or three concise lines.',
      'A second point captures the guidance change, risk, or analyst reaction worth noting.',
      'A closing point flags what to watch next for this story.',
    ];
    const popover = h('div', { className: 'qx-root' },
      h('div', { ref: popRef, className: 'qx-ni-ai-popover', role: 'dialog', 'aria-label': 'AI article summary', style: { left: pos.left + 'px', top: pos.top + 'px' } },
        h('div', { className: 'qx-ni-ai-pop-head' }, h('span', { className: 'qx-ni-ai-pop-mark', 'aria-hidden': 'true' }, h(AISparkle)), 'AI Article Summary'),
        h('div', { className: 'qx-ni-ai-pop-body' },
          h('h4', null, 'Key points'),
          h('ul', null, bullets.map((b, i) => h('li', { key: i }, b)))),
        h('div', { className: 'qx-ni-ai-pop-note' }, 'AI summary is generated automatically and is for informational use only. It does not constitute trade advice or a recommendation.'),
        h('div', { className: 'qx-ni-ai-pop-foot' }, h(RefreshIcon), 'Last updated ' + (updated || '9:47am'))));

    return h(React.Fragment, null,
      h('span', { ref: btnRef, className: 'qx-ni-ai', role: 'button', tabIndex: 0, 'aria-haspopup': 'dialog', 'aria-expanded': open, 'aria-label': name, title: name, onClick: toggle, onKeyDown },
        h(AISparkle)),
      open ? (ReactDOM && ReactDOM.createPortal ? ReactDOM.createPortal(popover, document.body) : popover) : null);
  }

  function LockIcon() {
    return h('svg', { className: 'qx-ni-lockglyph', width: 14, height: 14, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 2, strokeLinecap: 'round', strokeLinejoin: 'round', 'aria-hidden': 'true' },
      h('rect', { x: 3, y: 11, width: 18, height: 10, rx: 2 }),
      h('path', { d: 'M7 11V7a5 5 0 0 1 10 0v4' }));
  }

  /* ---- Media ---------------------------------------------------------- */
  function Media({ src, sourceInitials, alt }) {
    if (src) {
      return h('div', { className: 'qx-ni-media' },
        h('img', { className: 'qx-ni-thumb', src, alt: alt || '', loading: 'lazy' }));
    }
    // Branded fallback tile keeps alignment stable across a feed with patchy images.
    return h('div', { className: 'qx-ni-media qx-ni-media-fallback', 'aria-hidden': 'true' },
      h('span', { className: 'qx-ni-fallback-mark' }, (sourceInitials || 'QM').slice(0, 3)));
  }

  /* ---- Skeleton (mirrors configured anatomy) -------------------------- */
  function Skeleton({ r }) {
    const lines = (n, w) => Array.from({ length: n }, (_, i) =>
      h('span', { key: i, className: 'qx-ni-sk-line', style: { width: (Array.isArray(w) ? w[i] : w) || '100%' } }));
    const body = h('div', { className: 'qx-ni-sk-body' },
      r.metaPosition === 'top' ? h('span', { className: 'qx-ni-sk-meta' }) : null,
      h('div', { className: 'qx-ni-sk-title' }, lines(r.titleLines === 'full' ? 2 : r.titleLines, ['92%', '68%'])),
      r.showDescription ? h('div', { className: 'qx-ni-sk-desc' }, lines(Math.min(r.descriptionLines, 3), ['100%', '96%', '54%'])) : null,
      r.showBadgeRow ? h('div', { className: 'qx-ni-sk-badges' }, h('span', {}), h('span', {})) : null,
      r.metaPosition === 'bottom' ? h('span', { className: 'qx-ni-sk-meta' }) : null,
    );
    const media = r.showImage ? h('div', { className: 'qx-ni-sk-media' }) : null;
    return h('div', { className: 'qx-ni-inner' },
      r.imagePosition === 'trailing' ? [body, media] : [media, body].filter(Boolean));
  }

  /* ---- Component ------------------------------------------------------ */
  function QXNewsItem(props) {
    const {
      preset = 'feed',
      density = 'comfortable',
      state = 'default',
      // content
      title = 'Headline goes here',
      description = 'Story snippet goes here',
      source = 'Source name',
      timestamp = '2h ago',
      datetime,
      image,
      sourceInitials,
      imageAlt,
      symbol,
      symbolChange,
      sentiment = 'neutral',
      topic,
      aiLabel,
      signalLevel = 'high',
      href = '#',
      onActivate,
      ...rest
    } = props;

    const p = PRESETS[preset] || PRESETS.feed;
    const r = {
      metaPosition:     pick(props.metaPosition,     p.metaPosition,     'top'),
      titleLines:       pick(props.titleLines,       p.titleLines,       2),
      showDescription:  pick(props.showDescription,  p.showDescription,  true),
      descriptionLines: pick(props.descriptionLines, p.descriptionLines, 2),
      showImage:        pick(props.showImage,        p.showImage,        true),
      imagePosition:    pick(props.imagePosition,    p.imagePosition,    'leading'),
      showBadgeRow:     pick(props.showBadgeRow,     p.showBadgeRow,     true),
      showSymbol:       pick(props.showSymbol,       undefined,          !!symbol),
      showSentiment:    pick(props.showSentiment,    undefined,          false),
      showAI:           pick(props.showAI,           undefined,          false),
      showTopic:        pick(props.showTopic,        undefined,          !!topic),
      showSignalSpine:  pick(props.showSignalSpine,  undefined,          false),
      topicPosition:     pick(props.topicPosition,     undefined,         'badge'),   // 'badge' | 'top'
      sentimentPosition: pick(props.sentimentPosition, undefined,         'right'),   // 'right' | 'badge'
      aiPosition:        pick(props.aiPosition,        undefined,         'right'),    // 'right' | 'badge'
      minimalMeta:      p.minimalMeta || false,
    };

    const isLoading = state === 'loading';
    const isLocked = state === 'locked';
    const isRead = state === 'read';

    const dataAttrs = {
      className: 'qx-newsitem',
      'data-preset': preset,
      'data-density': density,
      'data-state': state,
      'data-image-pos': r.showImage ? r.imagePosition : 'none',
      'data-meta-pos': r.metaPosition,
      'data-signal': r.showSignalSpine ? signalLevel : undefined,
      'data-title-lines': r.titleLines,
      'data-desc-lines': r.descriptionLines,
    };

    // Loading skeleton is not a link and not focusable.
    if (isLoading) {
      return h('div', Object.assign({}, dataAttrs, { 'aria-hidden': 'true', role: 'presentation' }),
        h(Skeleton, { r }));
    }

    /* Reusable marks. */
    const symbolChip = (r.showSymbol && symbol)
      ? h('span', { key: 'sym', className: 'qx-ni-symbol' + (symbolChange != null ? (symbolChange >= 0 ? ' qx-ni-up' : ' qx-ni-down') : '') },
          symbol,
          symbolChange != null ? h('span', { className: 'qx-ni-symbol-chg' }, (symbolChange >= 0 ? '+' : '') + symbolChange.toFixed(2) + '%') : null)
      : null;
    const topicChip = (r.showTopic && topic) ? (key) => h('span', { key, className: 'qx-ni-topic' }, topic) : null;
    const sentimentChip = r.showSentiment ? h(SentimentIcon, { key: 'sent', sentiment }) : null;
    const aiBtn = r.showAI ? h(AIIcon, { key: 'ai', label: aiLabel, summary: props.aiSummary, updated: props.aiUpdated }) : null;

    /* Left badge row — symbol + (topic/sentiment/ai only when placed 'badge').
       Collapses entirely when empty, with no reserved space. */
    const badges = [];
    if (r.showBadgeRow) {
      if (symbolChip) badges.push(symbolChip);
      if (topicChip && r.topicPosition === 'badge') badges.push(topicChip('topic'));
      if (sentimentChip && r.sentimentPosition === 'badge') badges.push(sentimentChip);
      if (aiBtn && r.aiPosition === 'badge') badges.push(aiBtn);
    }
    const badgeRow = badges.length ? h('div', { className: 'qx-ni-badges' }, badges) : null;

    /* Topic kicker — own row above the headline (topicPosition='top'). */
    const kicker = (topicChip && r.topicPosition === 'top')
      ? h('div', { className: 'qx-ni-kicker' }, topicChip('kicker'))
      : null;

    /* Meta row — source · separator · relative time. One meta row at a time.
       Timestamp wrapped in <time datetime> with the absolute value. */
    const metaRow = h('div', { className: 'qx-ni-meta' },
      h('span', { className: 'qx-ni-source' }, source),
      h('span', { className: 'qx-ni-sep', 'aria-hidden': 'true' }, '·'),
      h('time', datetime ? { className: 'qx-ni-time', dateTime: datetime } : { className: 'qx-ni-time' }, timestamp),
    );
    const metaInMain = r.metaPosition !== 'right';

    const titleEl = h('h3', { className: 'qx-ni-title' }, title);
    const descEl = (r.showDescription && !r.minimalMeta)
      ? h('p', { className: 'qx-ni-desc' }, description)
      : null;

    // Main column DOM order: title → description → badges → meta → kicker
    // (headline first = accessible name; CSS `order` sets visual placement).
    const main = h('div', { className: 'qx-ni-main' },
      titleEl,
      descEl,
      badgeRow,
      metaInMain ? metaRow : null,
      kicker,
      isLocked ? h('span', { id: 'qx-ni-lock-desc', className: 'qx-sr-only' }, 'This story requires an upgrade to read.') : null,
    );

    // Right aside — sentiment + AI (their default home) and optional meta.
    const cluster = [];
    if (sentimentChip && r.sentimentPosition === 'right') cluster.push(sentimentChip);
    if (aiBtn && r.aiPosition === 'right') cluster.push(aiBtn);
    const asideKids = [];
    if (cluster.length) asideKids.push(h('div', { key: 'cluster', className: 'qx-ni-signal-cluster' }, cluster));
    if (!metaInMain) asideKids.push(h('div', { key: 'metaright', className: 'qx-ni-meta' },
      h('span', { className: 'qx-ni-source' }, source),
      h('span', { className: 'qx-ni-sep', 'aria-hidden': 'true' }, '·'),
      h('time', datetime ? { className: 'qx-ni-time', dateTime: datetime } : { className: 'qx-ni-time' }, timestamp)));
    const aside = asideKids.length ? h('div', { className: 'qx-ni-aside' }, asideKids) : null;

    const body = h('div', { className: 'qx-ni-body' }, main, aside);

    const media = r.showImage
      ? h('div', { className: 'qx-ni-media-wrap' },
          h(Media, { src: image, sourceInitials, alt: imageAlt }),
          isLocked ? h('span', { className: 'qx-ni-media-lock', 'aria-hidden': 'true' }, h(LockIcon)) : null)
      : null;

    const inner = h('div', { className: 'qx-ni-inner' },
      r.imagePosition === 'trailing' ? [body, media] : [media, body]);

    const handleClick = onActivate ? (e) => { e.preventDefault(); onActivate(props); } : undefined;

    return h('a', Object.assign({
      href,
      onClick: handleClick,
      'aria-label': title,
      'aria-describedby': isLocked ? 'qx-ni-lock-desc' : undefined,
    }, dataAttrs, rest),
      isLocked ? h('span', { className: 'qx-ni-lock-badge' }, h(LockIcon), 'Upgrade to read') : null,
      inner);
  }

  QXNewsItem.PRESETS = PRESETS;
  return QXNewsItem;
});
