import * as React from 'react';

export type QXNewsItemPreset = 'feed' | 'editorial' | 'compact' | 'lead' | 'embed';
export type QXNewsItemDensity = 'comfortable' | 'compact';
export type QXNewsItemState = 'default' | 'hover' | 'active' | 'focus' | 'read' | 'loading' | 'locked';
export type QXTitleLines = 1 | 2 | 3 | 'full';
export type QXImagePosition = 'leading' | 'trailing' | 'above';
export type QXSentiment = 'positive' | 'negative' | 'neutral';
export type QXSignalLevel = 'high' | 'medium' | 'low';

export interface QXNewsItemProps extends Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, 'title'> {
  /** Named prop bundle. Sets defaults; individual props stay overridable. @default 'feed' */
  preset?: QXNewsItemPreset;
  /** Adjusts padding / line-height without changing which parts are present. @default 'comfortable' */
  density?: QXNewsItemDensity;
  /** Interactive / render state. @default 'default' */
  state?: QXNewsItemState;

  /** Headline. Required content; also the row's accessible name. */
  title?: string;
  /** Story snippet. Shown when showDescription. */
  description?: string;
  /** Source name (own token, kept out of the headline string). */
  source?: string;
  /** Relative timestamp, e.g. "2h ago". */
  timestamp?: string;
  /** Absolute ISO value for the <time datetime> attribute. */
  datetime?: string;
  /** Thumbnail URL. When absent and showImage is true, a branded fallback tile renders. */
  image?: string;
  /** Initials for the branded fallback tile. */
  sourceInitials?: string;
  /** Media alt text — "" for a decorative thumbnail, a real description only when it conveys unique info. */
  imageAlt?: string;

  /** Ticker for the symbol chip. */
  symbol?: string;
  /** Optional percent change shown inside the symbol chip, coloured by sign. */
  symbolChange?: number;
  /** Sentiment tone (semantic token + shape, never colour alone). @default 'neutral' */
  sentiment?: QXSentiment;
  /** Topic chip label. */
  topic?: string;
  /** Accessible name for the AI icon. @default 'Summary generated by AI' */
  aiLabel?: string;
  /** Importance rank driving the signal spine colour. @default 'high' */
  signalLevel?: QXSignalLevel;

  /** Line clamp on the headline. Preset-defaulted. */
  titleLines?: QXTitleLines;
  /** Preset-defaulted. */
  showDescription?: boolean;
  /** 1 | 2 | 3. Preset-defaulted. Hidden when showDescription is false. */
  descriptionLines?: 1 | 2 | 3;
  /** Preset-defaulted. */
  showImage?: boolean;
  /** Preset-defaulted. Hidden when showImage is false. */
  imagePosition?: QXImagePosition;
  /** Badge-row members. */
  showSymbol?: boolean;
  showSentiment?: boolean;
  showAI?: boolean;
  showTopic?: boolean;
  /** Meta row placement (only one meta row renders). Preset-defaulted. */
  metaPosition?: 'top' | 'bottom';
  /** 3px importance spine on the row's leading edge. @default false */
  showSignalSpine?: boolean;

  /** Called with the props on activation instead of following href (opens article / upgrade modal). */
  onActivate?: (props: QXNewsItemProps) => void;
}

/** One row component for every news story across QSweb, Quotestream Mobile, Research Hub and QX/QMOD widgets. */
export function QXNewsItem(props: QXNewsItemProps): JSX.Element;
export default QXNewsItem;
